### ISSUE TITLE
Add everything still needed for the v1 release

### ISSUE THREAD

**Issue by coralvanda** [StratoDem/strato-query#2]
## Description

Update the app with the remaining items needed for a v1 release.

## Tasks

- [x] fill out `setup.py`
- [x] update CHANGELOG
- [x] add tests
- [x] fill out `README.md`

**Comment by coralvanda** [comment]
@mjclawar am I missing anything else we'll want/need for v1?

**Comment by mjclawar** [comment]
I don't think so. Perhaps check by installing directly from GH in the repo using this to see if it has the basic requirements?
